[data_source]
source = 'reddit'
url = 'https://www.reddit.com/r/AskReddit/comments/1ejq3hs/snap_your_fingers_and_make_anyone_alive_president/'
comments_qty = 10
samples = false
default_name = true

[html_generation]
enabled = true
version = 'v4'

[audio_generation]
enabled = false
tts_library = 'tts'

[audio_collection]
enabled = false
source_folder = ''

[video_generation]
enabled = false
extension = 'mp4'

[combining]
enabled = false
