[output]
folder = ''

[data_source]
source = 'reddit'
urls = []
comments_qty = 10
samples = true

[html_generation]
enabled = true
version = 'v3'

[audio_generation]
enabled = true
tts_library = 'tts'

[video_generation]
enabled = true

[combining]
enabled = true
