[data_source]
source = 'reddit'
url = ''
comments_qty = 10
samples = true

[html_generation]
enabled = true
version = 'v4'

[audio_generation]
enabled = false
tts_library = 'tts'

[video_generation]
enabled = false
extension = 'mp4'

[combining]
enabled = false
